// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"sync"

	internal "github.com/briangreenhill/blackbox/pkg/internal"
	mock "github.com/stretchr/testify/mock"
)

// Checker is an autogenerated mock type for the Checker type
type ConcurrentChecker struct {
	mock.Mock
	mu sync.Mutex
	Wg sync.WaitGroup
}

// DoCheck provides a mock function with given fields: _a0
func (_m *ConcurrentChecker) DoCheck(_a0 internal.Target) error {
	defer _m.Wg.Done()
	ret := _m.Called(_a0)

	var r0 error
	_m.mu.Lock()
	if rf, ok := ret.Get(0).(func(internal.Target) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}
	_m.mu.Unlock()

	return r0
}
