name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.36
        args: -E goimports
      env:
        CGO_ENABLED: 0
    - name: Test
      run: make test
      env:
        CGO_ENABLED: 0
